# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rsvp_server.models.base_model_ import Model
from rsvp_server import util


class Login(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, user: str=None, _pass: str=None):  # noqa: E501
        """Login - a model defined in Swagger

        :param user: The user of this Login.  # noqa: E501
        :type user: str
        :param _pass: The _pass of this Login.  # noqa: E501
        :type _pass: str
        """
        self.swagger_types = {
            'user': str,
            '_pass': str
        }

        self.attribute_map = {
            'user': 'user',
            '_pass': 'pass'
        }

        self._user = user
        self.__pass = _pass

    @classmethod
    def from_dict(cls, dikt) -> 'Login':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The login of this Login.  # noqa: E501
        :rtype: Login
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> str:
        """Gets the user of this Login.


        :return: The user of this Login.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this Login.


        :param user: The user of this Login.
        :type user: str
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def _pass(self) -> str:
        """Gets the _pass of this Login.


        :return: The _pass of this Login.
        :rtype: str
        """
        return self.__pass

    @_pass.setter
    def _pass(self, _pass: str):
        """Sets the _pass of this Login.


        :param _pass: The _pass of this Login.
        :type _pass: str
        """
        if _pass is None:
            raise ValueError("Invalid value for `_pass`, must not be `None`")  # noqa: E501

        self.__pass = _pass
